
# ESTE ES UN PROGRAMA HOLA MUNDO

'''
ESTE ES UN EJERCICIO DE CLASE
PARA COMPRENDER LA SINTAXIS BASICA DE PYTHON
CUANDO VARIAS FRASES O PARRAFOS, SE UTILIZA
ESTE TIPO DE COMENTARIO ENTRE COMILLAS
'''

print("Hola mundo!")



